services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:SomeRandomKeyHere
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/database.sqlite
