services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/database.sqlite

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
